
title: pi-theta.com
email: bineetdubeybrahmin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website for services and Blogs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bineetdubey.github.io" # the base hostname & protocol for your site
twitter_username: bineet_brahmin
github_username:  bineetdubey

# Build settings
markdown: kramdown
